import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import venuesRouter from "./venues";
import adminRouter from "./admin";
import bookingsRouter from "./bookings";
import paymentsRouter from "./payments";
import favouritesRouter from "./favourites";
import playerAccountRouter from "./player-account";
import playerAvatarRouter from "./player-avatar";
import ownerAccountRouter from "./owner-account";
import ownerNotificationsRouter from "./owner-notifications";
import playerNotificationsRouter from "./player-notifications";
import subscriptionsRouter from "./subscriptions";
import matchStatisticsRouter from "./match-statistics";
import leaderboardRouter from "./leaderboard";
import eliteRouter from "./elite";
import tournamentsRouter from "./tournaments";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(venuesRouter);
router.use(adminRouter);
router.use(bookingsRouter);
router.use(paymentsRouter);
router.use(favouritesRouter);
router.use(playerAccountRouter);
router.use(playerAvatarRouter);
router.use(ownerAccountRouter);
router.use(ownerNotificationsRouter);
router.use(playerNotificationsRouter);
router.use(subscriptionsRouter);
router.use(matchStatisticsRouter);
router.use(leaderboardRouter);
router.use(eliteRouter);

router.use(tournamentsRouter);
export default router;
